version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  api-server:
    image: sanbonai06/tify-server
    container_name: backend
    build:
      context: './Api'
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis

#  front:
#    image: simmigyeong/depromeet-fe
#    container_name: front
#    build:
#      context: '../'
#      dockerfile: Dockerfile
#      args:
#        ENV_VARIABLE: ${ENV_VARIABLE}
#        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
#    expose:
#      - 3000
#    ports:
#      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
