spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬

slack:
  webhook:
    id: ${SLACK_CHANNEL_ID:}

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework