spring:
  profiles:
    include:
      - domain
      - core
      - infrastructure
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}

slack:
  webhook:
    id: ${SLACK_CHANNEL_ID:}

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework