auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:3600}
    issuer: ${JWT_ISSUER:test}


oauth2:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
  apple:
    base-url: ${APPLE_BASE_URL}
    team-id: ${APPLE_TEAM_ID}
    client-url: ${APPLE_CLIENT}
    log-in-key: ${APPLE_LOGIN_KEY}
    redirect-url: ${APPLE_REDIRECT}
    key-path: ${APPLE_KEY_PATH}
    key: ${APPLE_KEY}

#s3:
#  region: ${S3_REGION}
#  access-key: ${S3_ACCESS_KEY}
#  secret-key: ${S3_SECRET_KEY}
#  bucket-name: ${S3_BUCKET_NAME}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      name: ${S3_REGION}
      static: ap-northeast-2
    stack:
      auto: false